### ISSUE TITLE
Github Actions でアノテーションをつける

### ISSUE THREAD

**Issue by t-yng** [t-yng/cspell-test#3]
### 出力をフォーマットする
https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

### reviewdogを利用する
https://github.com/reviewdog/reviewdog

**Comment by t-yng** [comment]
**出力のフォーマットの場合**

出力のやり方に自由度が無く、少し複雑な正規表現を書く必要があるので、保守性が低くなる。

```yml
# check-spell.yml
name: check-spell
on: [ pull_request ]
jobs:
  check-spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys:
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn install
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/check-spell-problem-matcher.json"
      - name: check spell
        run: yarn cspell index.ts
```

```json
// check-spell-problem-matcher.json
{
  "problemMatcher": [
    {
      "owner": "spell-check",
      "pattern": [
        {
          "regexp": "^/.+/(.+?):(\\d+):.+ - (.+)",
          "file": 1,
          "line": 2,
          "message": 3
        }
      ]
    }
  ]
}
```

**Comment by t-yng** [comment]
reviewdog

[Playground](https://reviewdog.github.io/errorformat-playground/?efms=%25f%3A%25l%3A%25c%5C+-%5C+%25m%0A&text=Users%2Ftomohiro%2Fworkspace%2Fplaygournd%2Fcspell-test%2Findex.ts%3A1%3A7+-+Unknown+word+%28setsupport%29)で抽出方法を試せる

`.reviewdog.yml` で実行コマンドとエラーフォーマットを制御できる

```
runner:
  cspell:
    cmd: yarn cspell index.ts
    errorformat:
      - "%f:%l:%c\ -\ %m"
    level: error
```

```
review dog -conf=./.github/conf/.reviewdog.yml -reporter=github-pr-check
```

filter-modeについて

`-filter-mode` を指定することで、どの修正に対して指摘コメントを付けるか制御ができる。
デフォルトは `added` になっており、PRに含まれる修正差分に対してだけ指摘される。
設定可能なモードは reporter とも関係している。

設定一覧と対応表は[ドキュメント](https://github.com/reviewdog/reviewdog#filter-mode)を参照
